// Generated by deploy-cf.sh - do not edit.
export const ASSET_SIZES = {
  "/social/shieldfont-social-16x9.mp4": 4301097,
  "/social/shieldfont-social-4x5.mp4": 3375681,
  "/social/shieldfont-social-9x16.mp4": 3480073,
  "/videos/shieldfont-tutorial.mp4": 22058085
};
